# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "boxman/ubuntu-20.04-minimal"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox"

  config.vm.provider :virtualbox do |v|
    v.memory = 8192
    v.cpus = 1
    v.linked_clone = true
  end

  # Define two VMs with static private IP addresses.
  boxes = [
    { :name => "Controller", :ip => "192.168.42.11" },
    { :name => "ComputeNode", :ip => "192.168.42.12" },
  ]

  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name] + ".multi-node.test"
      config.vm.network :private_network, ip: opts[:ip]

      # Provision all the VMs using Ansible after last VM is up.
        config.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "main.yml"
          ansible.inventory_path = "inventory"
          ansible.limit = "all"
        end
    end
  end
end